apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-deploy
spec:
  type: ClusterIP
  selector:
    app: backend-deploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
