apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
  labels:
    app: frontend-deploy
spec:
  type: LoadBalancer
  selector:
    app: frontend-deploy
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 5000
      nodePort: 31000  

